name: tmux-devmode
version: 2.6
summary: tmux is a terminal multiplexer (non-official)
description: |
 it enables a number of terminals (or windows), each running a separate program,
 to be created, accessed, and controlled from a single screen. tmux may be
 detached from a screen and continue running in the background, then later
 reattached.
grade: devel
confinement: devmode

apps:
  tmux:
    command: bin/tmux
    plugs:
      - home

parts:
  tmux:
    plugin: autotools
    source: https://github.com/tmux/tmux.git
    source-type: git
    build-packages: [libevent-dev, libncurses5-dev, pkg-config]
    stage-packages: [libevent-2.0-5, libncurses5]
